apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: rack1-ippool
spec:
  cidr: 10.10.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "rack1"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: rack2-ippool
spec:
  cidr: 10.10.2.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "rack2"
