apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: frontend-deployment
  template:   
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: "KrylovAE"
        - name: REACT_APP_COMPANY_NAME
          value: "ITMO"
